'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Factory, Landmark, Network, ArrowRight, FileText, ArrowUpRight, CheckCircle2, Layers3, CircleHelp, RotateCcw, Download, Send, ShieldCheck, LockKeyhole, GitBranch, AlertTriangle, Check, ExternalLink } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { scenario, initialState, applyAction, canApply, currentEstimate, latestPackage, bankView, opsView, quote, getFindings, restoreState, type State, type Role, type Action, type ShareField, type Package, type Estimate } from '@/lib/demo/engine';
const STORAGE='transitionops.demo.v1';
const n=(v:number)=>Math.round(v).toLocaleString('ko-KR');
const won=(v:number)=>`${n(v/10000)}만원`;
const roleNames:Record<Role,string>={manufacturer:'제조기업',bank:'은행 RM',ops:'운영 담당자'};
const clock=(s:string)=>new Date(s).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
type ModelContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};

function EstimateDetails({e}:{e:Estimate}){return <div className="estimate-detail"><div className="energy-bar"><div><span>기준 계통</span><i style={{width:'100%'}}/><b>{n(e.baseline)} kWh</b></div><div><span>교체안</span><i className="green" style={{width:`${e.proposed/e.baseline*100}%`}}/><b>{n(e.proposed)} kWh</b></div></div><div className="calc-facts"><span>동일 운전 <b>{n(e.hours)}h/년</b></span><span>가상 단가 <b>{e.tariff}원/kWh</b></span><span>예상 절감률 <b>{e.savingPercent.toFixed(1)}%</b></span><span>단순 회수기간 <b>{e.payback.toFixed(2)}년</b></span></div><p className="source-note">∑(부하별 전력 × 시간) + 드라이어 전력 × 시간. 합성 표본의 연간 환산이며 실측 성과가 아닙니다. 회수기간은 부가세 제외, 금융·유지비 미반영.</p></div>}
function PackageBody({p}:{p:Package}){return <div className="package-body"><div className="package-line"><span>전달 목적</span><b>{p.purpose}</b></div><div className="package-line"><span>대상</span><b>{p.project.company} / {p.project.id}</b></div><div className="package-line"><span>설비 범위</span><p>{p.scope}</p></div><div className="package-line"><span>견적 v{p.quoteVersion}</span><p>{p.quote.description} · 공급가 {won(p.quote.capex)} · 부가세 {won(p.quote.vat)}</p></div>{p.estimate?<EstimateDetails e={p.estimate}/>:<div className="notice amber">전력 추정 근거 미포함 · 계측 경계와 운전 가정을 보완해야 합니다.</div>}<h3 className="small-heading">승인된 근거 발췌</h3>{p.sources.map(x=><div className="excerpt" key={x.id}><code>{x.id}</code><p>{x.excerpt}</p></div>)}<h3 className="small-heading">별도로 확인할 항목</h3><ul className="plain-list">{p.openItems.map(x=><li key={x}>{x}</li>)}</ul><p className="source-note">{p.approval} · {new Date(p.approvedAt).toLocaleString('ko-KR')} · 합성 시연 자료</p></div>}

export default function Home(){
 const [state,setState]=useState<State>(initialState);
 const stateRef=useRef(state);
 const [role,setRole]=useState<Role>('manufacturer');
 const roleRef=useRef(role);
 const [ready,setReady]=useState(false);
 const [message,setMessage]=useState('');
 const [storageWarning,setStorageWarning]=useState('');
 const [modal,setModal]=useState<'share'|'basis'|'quote'|'guide'|null>(null);
 const [doc,setDoc]=useState<{title:string;content:string}|null>(null);
 const [selectedPackage,setSelectedPackage]=useState<Package|null>(null);
 const [resetOpen,setResetOpen]=useState(false);
 const [checks,setChecks]=useState<boolean[]>([false,false,false]);
 const [fields,setFields]=useState<ShareField[]>(['scope','quote']);
 const [consent,setConsent]=useState(false);
 const [selectionIssue,setSelectionIssue]=useState('');
 const estimate=currentEstimate(state), currentQuote=quote(state.quoteVersion), latest=latestPackage(state), bank=bankView(state), ops=opsView(state), findings=getFindings(state);
 const commit=useCallback((next:State)=>{stateRef.current=next;setState(next);try{localStorage.setItem(STORAGE,JSON.stringify(next));setStorageWarning('')}catch{setStorageWarning('브라우저 저장을 사용할 수 없어 현재 화면에서만 진행됩니다.')}},[]);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE);if(saved){const parsed=restoreState(JSON.parse(saved));if(parsed){stateRef.current=parsed;setState(parsed)}else setStorageWarning('이전 저장 형식이 달라 새 시연으로 시작했습니다.')}}catch{setStorageWarning('이전 저장을 읽지 못해 새 시연으로 시작했습니다.')}setReady(true)},[]);
 const run=useCallback((action:Action,actor=roleRef.current)=>{const next=applyAction(stateRef.current,actor,action);commit(next);return next},[commit]);
 const act=(action:Action,success:string)=>{try{run(action);setMessage(success);return true}catch(e){setMessage(e instanceof Error?e.message:'작업을 완료하지 못했습니다.');return false}};
 const changeRole=(value:string)=>{if(['manufacturer','bank','ops'].includes(value)){roleRef.current=value as Role;setRole(value as Role);setMessage('');setDoc(null)}};
 const openReview=(kind:'basis'|'quote')=>{setChecks([false,false,false]);setModal(kind)};
 const openShare=()=>{setFields(estimate?['scope','quote','energy']:['scope','quote']);setConsent(false);setSelectionIssue('');setModal('share')};
 function exportPackage(p:Package){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));a.href=url;a.download=`${p.id}.json`;a.click();URL.revokeObjectURL(url)}
 useEffect(()=>{
  const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tools=[{name:'read_transition_case',title:'현재 역할의 투자 건 읽기',description:'Read the currently selected demo role. Manufacturer data is not included in bank or operations results.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('빈 객체가 필요합니다.');const s=stateRef.current;return roleRef.current==='bank'?bankView(s):roleRef.current==='ops'?opsView(s):{quoteVersion:s.quoteVersion,findings:getFindings(s),estimate:currentEstimate(s),latestSharedId:latestPackage(s)?.id??null}}},
  {name:'request_transition_evidence',title:'은행 보완 요청 생성',description:'Create a real demo evidence request for the latest received package. Available only in the bank preview; does not contact an institution.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('빈 객체가 필요합니다.');const s=run({type:'request'});setMessage('은행 보완 요청을 만들었습니다.');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {request:s.requests.at(-1)}}}];
  for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{/* Optional browser integration. */}}
  return()=>lifecycle.abort();
 },[run]);
 const displayedEstimate=role==='manufacturer'?estimate:bank.package?.estimate;
 const activeDocs=scenario.documents.filter(d=>['DOC-01','DOC-02','DOC-03','DOC-07'].includes(d.id)||(d.id==='DOC-04'&&state.basisReceived)||(d.id==='DOC-05'&&state.quoteVersion===2)||(d.id==='DOC-06'&&state.requests.length>0));
 const roleStatus=role==='manufacturer'?(state.pending?'승인본 전달 대기':!estimate?'자료 보완 필요':latest?.sourceRevision===state.sourceRevision?'공유본 전달 완료':'공유 승인 대기'):role==='bank'?(!bank.package?'자료 수신 대기':bank.reviewed?'수신 자료 검토 완료':bank.reviewStale?'새 버전 재검토 필요':'공유 자료 검토 대기'):(ops.pending?'전달 재처리 필요':'전달 이력 확인');
 return <div className="workspace"><header className="topbar"><a className="brand" href="/"><Layers3 size={24}/>Transition<span>Ops</span></a><div className="top-actions"><span className="demo-pill">DEMO · 합성 기업자료</span><Button variant="ghost" className="help-button" onClick={()=>setModal('guide')}><CircleHelp size={18}/><span>데모 안내</span></Button></div></header>
 <div className="workspace-body"><div className="role-header"><p className="eyebrow">전환투자 워크스페이스 <span className="role-preview">/ 역할 미리보기</span></p><Tabs value={role} onValueChange={v=>changeRole(String(v))}><TabsList className="role-tabs"><TabsTrigger value="manufacturer"><Factory/>제조기업</TabsTrigger><TabsTrigger value="bank"><Landmark/>은행 RM</TabsTrigger><TabsTrigger value="ops"><Network/>운영</TabsTrigger></TabsList></Tabs></div>
 <header className="project-heading"><div><p className="breadcrumb">{role==='bank'?'금융 검토 공간':role==='ops'?'기술 운영 공간':'가온정밀 데모제조(가상)'} / {scenario.scenario_id}</p><h1>{role==='ops'?'승인 자료 전달·운영':'공기압축기 계통 개선'}</h1><p>{role==='manufacturer'?'설비와 견적의 근거를 준비하고, 필요한 자료만 공유하세요.':role==='bank'?'기업이 승인해 전달한 자료를 검토하고, 부족한 근거를 요청하세요.':'업무 판단과 분리된 전달 상태·오류·변경 이력을 확인하세요.'}</p></div><span className={`status ${roleStatus.includes('완료')?'good':'warn'}`}>{roleStatus}</span></header>
 <div className="flowline"><div className={displayedEstimate?'active':''}><span>01</span><b>제조 근거 준비</b>{displayedEstimate&&<Check size={16}/>}</div><ArrowRight/><div className={latest?'active':''}><span>02</span><b>승인 자료 공유</b>{latest&&<Check size={16}/>}</div><ArrowRight/><div className={bank.reviewed?'active':''}><span>03</span><b>은행 검토·보완</b>{bank.reviewed&&<Check size={16}/>}</div></div>
 {storageWarning&&<div className="notice amber" role="status">{storageWarning}</div>}{message&&<div className="feedback" role="status" aria-live="polite"><CheckCircle2 size={18}/>{message}<button aria-label="알림 닫기" onClick={()=>setMessage('')}>×</button></div>}
 {role==='manufacturer'&&<>
 <div className="metric-grid"><div><span>현재 견적 · v{state.quoteVersion}</span><strong>{n(currentQuote.capex/10000)}<small>만원</small></strong><p>{currentQuote.description} · 부가세 별도</p></div><div><span>예상 전력 절감 / 연간</span><strong className={!estimate?'muted':''}>{estimate?n(estimate.saving):'산정 대기'}{estimate&&<small>kWh</small>}</strong><p>{estimate?`가상 운전 조건 · 예상 절감 ${won(estimate.annualCostSaving)}/년`:'계측 경계·운전 조건 검토 필요'}</p></div><div><span>은행에 마지막으로 전달한 자료</span><strong>{latest?`r${latest.revision} / 견적 v${latest.quoteVersion}`:'아직 없음'}</strong><p>{state.pending?'새 승인본은 전달 대기 중':latest?`현재 내부 견적 v${state.quoteVersion}와 별도 보관`:'미산정 항목을 포함한 상담 준비본도 공유 가능'}</p></div></div>
 <div className="work-grid"><div className="stack"><section className="panel"><div className="section-heading"><h2>투자 근거</h2><span className="tiny"><LockKeyhole size={13}/> 제조 내부 · {activeDocs.length}개</span></div>{activeDocs.map(d=><button className="document-row doc-button" key={d.id} onClick={()=>setDoc({title:d.title,content:d.content})}><FileText/><div><b>{d.title}</b><p>{d.id} · {d.id==='DOC-04'&&!state.basisReviewed?'수신 후 검토 대기':d.id==='DOC-05'&&!state.quoteReviewed?'변경 검토 대기':'가상 원문'} · v{d.version}</p></div><ArrowUpRight size={17}/></button>)}<div className="document-actions"><Button variant="outline" disabled={!ready||state.basisReceived} onClick={()=>act({type:'receive_basis'},'시설 회신을 불러왔습니다. 경계와 생산 조건을 확인해 주세요.')}><FileText/>시설 회신 불러오기</Button><Button variant="outline" disabled={!ready||!canApply(state,role,{type:'receive_quote'})} onClick={()=>act({type:'receive_quote'},'변경 견적 v2를 받았습니다. 은행의 기존 공유본은 유지됩니다.')}><GitBranch/>변경 견적 v2 불러오기</Button></div></section>
 {estimate&&<section className="panel"><div className="section-heading"><h2>같은 계통, 같은 운전 조건</h2><span className="status neutral">조건부 추정</span></div><EstimateDetails e={estimate}/></section>}
 {state.quoteVersion===2&&<section className="panel"><div className="section-heading"><h2>견적 변경 영향</h2><span className="status warn">v1 → v2</span></div><Table><TableHeader><TableRow><TableHead>변경 항목</TableHead><TableHead>v1</TableHead><TableHead>v2</TableHead></TableRow></TableHeader><TableBody>{[['설비 범위','기존 드라이어 유지','신규 드라이어 포함'],['공급가','4,800만원','5,500만원'],['부가세 포함 지급액','5,280만원','6,050만원'],['예상 절감 전력 / 년','35,200 kWh','39,200 kWh'],['단순 회수기간','9.09년','9.35년']].map(r=><TableRow key={r[0]}>{r.map((c,i)=><TableCell key={i}>{c}</TableCell>)}</TableRow>)}</TableBody></Table><p className="source-note">같은 합성 운전 조건으로 비교한 변경안 미리보기. 검토·공유 승인 전에는 은행의 기존 자료를 바꾸지 않습니다.</p></section>}
 {state.requests.length>0&&<section className="panel"><div className="section-heading"><h2>은행에서 온 보완 요청</h2><span className="tiny">{state.requests.length}건</span></div>{state.requests.map(r=><div className="request" key={r.id}><div><code>{r.id} / {r.packageId}</code><span className={`status ${r.status==='answered'?'good':'warn'}`}>{r.status==='answered'?'근거 확인됨':'보완 요청'}</span></div><p>{r.text}</p></div>)}</section>}</div>
 <aside className="stack"><section className="panel next-panel"><div className="section-heading"><h2>검토 초안 · 다음 행동</h2><span className="tiny">근거 규칙 기반</span></div>{findings.map(f=><article className={`finding ${f.severity}`} key={f.id}><div className="finding-owner">{f.severity==='blocking'?<AlertTriangle size={15}/>:<CheckCircle2 size={15}/>} {f.owner}</div><h3>{f.title}</h3><p>{f.body}</p><div className="source-chips">{f.sources.map(id=><button key={id} onClick={()=>{const d=activeDocs.find(d=>d.id===id);if(d)setDoc({title:d.title,content:d.content})}} disabled={!activeDocs.some(d=>d.id===id)}>{id}<ArrowUpRight size={11}/></button>)}</div></article>)}{state.basisReceived&&!state.basisReviewed&&<Button className="primary-action full" onClick={()=>openReview('basis')}>운전 근거·생산 조건 확인 <ArrowRight/></Button>}{state.quoteVersion===2&&!state.quoteReviewed&&<Button className="primary-action full" onClick={()=>openReview('quote')}>변경 영향 확인 <ArrowRight/></Button>}</section>
 <section className="panel share-card"><div className="section-heading"><h2>은행 공유 준비</h2><ShieldCheck size={20}/></div><p>{state.pending?'승인은 완료됐지만 전달이 실패했습니다. 승인본을 유지한 채 운영 화면에서 다시 전달하세요.':estimate?'선택한 집계·견적·가정과 근거 발췌만 전달합니다. 고객명·레시피·원시 로그는 공유본에서 제외됩니다.':'절감량은 미산정으로 표시하고 견적·미확인 항목부터 상담할 수 있습니다.'}</p><Button className="primary-action full" disabled={!ready||!!state.pending||!state.quoteReviewed} onClick={openShare}><Send/> {estimate?'공유 범위 확인·승인':'상담 준비본 공유'}</Button>{(latest||state.pending)&&<Button variant="ghost" className="full secondary-action" onClick={()=>changeRole(state.pending?'ops':'bank')}>{state.pending?'운영에서 재전달':'은행 수신 화면 보기'}<ArrowRight/></Button>}</section>
 </aside></div></>}
 {role==='bank'&&<>
 {!bank.package?<div className="empty-state"><Landmark size={32}/><h2>기업의 승인 자료를 기다리고 있어요.</h2><p>제조기업 화면에서 상담 준비본을 공유하면 여기에서 검토할 수 있습니다.</p><Button className="primary-action" onClick={()=>changeRole('manufacturer')}>제조기업으로 이동 <ArrowRight/></Button></div>:<><div className="metric-grid"><div><span>수신 자료 · r{bank.package.revision}</span><strong>{won(bank.package.quote.capex)}</strong><p>견적 v{bank.package.quoteVersion} · 공급가</p></div><div><span>공유된 예상 전력 절감</span><strong>{bank.package.estimate?n(bank.package.estimate.saving):'미포함'}{bank.package.estimate&&<small>kWh/년</small>}</strong><p>기업이 승인한 조건부 추정</p></div><div><span>금융 검토 상태</span><strong>{bank.reviewed?'자료 확인됨':'근거 검토 중'}</strong><p>대출 승인·금리·한도 결정과 별도</p></div></div>{bank.reviewStale&&<div className="notice amber"><GitBranch size={18}/><div><b>새 공유본이 도착했습니다.</b><p>이전 자료의 검토 기록을 유지하고, 새 견적과 투자 근거를 다시 확인하세요.</p></div></div>}<div className="work-grid"><section className="panel"><div className="section-heading"><h2>기업이 승인한 자료</h2><Button variant="outline" onClick={()=>exportPackage(bank.package!)}><Download/>JSON 내려받기</Button></div><PackageBody p={bank.package}/></section><aside className="stack"><section className="panel next-panel"><div className="section-heading"><h2>RM 검토</h2><span className="tiny">수신본 기준</span></div><h3>{bank.package.estimate?'근거와 남은 조건을 확인하세요.':'계측 범위와 운전 근거가 필요해요.'}</h3><p>{bank.package.estimate?'공유된 견적과 전력 추정은 상담 준비에 사용할 수 있습니다. 미산정 탄소 항목, 설치 후 기술 확인, 신용·담보 조건은 별도 검토로 남습니다.':'공장 전체 전력은 압축기 계통의 기준 소비가 아닙니다. 필요한 항목과 이유를 제조 담당자에게 요청하세요.'}</p><Button className="primary-action full" disabled={!canApply(state,role,{type:'request'})} onClick={()=>act({type:'request'},'제조기업에 보완 요청을 등록했습니다. 실제 기관으로 전송되지는 않습니다.')}><Send/>보완 요청 만들기</Button><Button variant="outline" className="full secondary-action" disabled={!canApply(state,role,{type:'review_bank'})} onClick={()=>act({type:'review_bank'},'수신 자료의 검토 기록을 남겼습니다. 금융 승인은 별도입니다.')}><CheckCircle2/>수신 자료 검토 기록</Button><Button variant="ghost" className="full secondary-action" onClick={()=>changeRole('manufacturer')}>제조 보완 화면으로 <ArrowRight/></Button></section><section className="panel"><div className="section-heading"><h2>받은 버전</h2><span className="tiny">{bank.history.length}개</span></div>{[...bank.history].reverse().map(p=><button className="history-item" key={p.id} onClick={()=>setSelectedPackage(p)}><GitBranch size={18}/><div><b>r{p.revision} · 견적 v{p.quoteVersion}</b><p>{clock(p.approvedAt)} · {won(p.quote.capex)}</p></div><ArrowUpRight size={16}/></button>)}</section><div className="boundary-note"><LockKeyhole size={19}/><p>이 화면과 내려받기는 승인된 공유본만 표시합니다. 제조 원문과 은행 내부 심사 정책은 합치지 않습니다.</p></div></aside></div></>}
 </>}
 {role==='ops'&&<><div className="metric-grid"><div><span>전달 완료</span><strong>{ops.deliveredCount}<small>건</small></strong><p>서로 다른 승인 자료 버전</p></div><div><span>전달 대기</span><strong>{ops.pending?1:0}<small>건</small></strong><p>{ops.pending?ops.pending.id:'대기 중인 승인본 없음'}</p></div><div><span>기록된 처리 이력</span><strong>{ops.events.length}<small>건</small></strong><p>현재 브라우저의 시연 기록</p></div></div><div className="work-grid"><section className="panel"><div className="section-heading"><h2>처리 이력</h2><span className="tiny">원문·금액 미표시</span></div>{ops.events.length?<Table><TableHeader><TableRow><TableHead>시간·역할</TableHead><TableHead>처리</TableHead><TableHead>참조</TableHead><TableHead>상태</TableHead></TableRow></TableHeader><TableBody>{[...ops.events].reverse().map(e=><TableRow key={e.id}><TableCell>{clock(e.at)}<span className="table-sub">{roleNames[e.role]}</span></TableCell><TableCell>{e.name}</TableCell><TableCell><code>{e.reference}</code></TableCell><TableCell><span className={`status ${e.status==='done'?'good':'warn'}`}>{e.status==='done'?'완료':e.status==='failed'?'실패':'대기'}</span></TableCell></TableRow>)}</TableBody></Table>:<p className="empty-inline">제조 자료 준비·공유를 시작하면 처리 이력이 쌓입니다.</p>}</section><aside className="stack"><section className="panel next-panel"><div className="section-heading"><h2>전달 실패·복구 시연</h2><Network size={21}/></div><p>다음 공유의 전달 실패를 재현할 수 있습니다. 이미 승인한 자료를 보관하고, 재전달해도 같은 버전이 중복 생성되지 않게 처리합니다.</p><Button variant="outline" className="full secondary-action" disabled={ops.failNextDelivery||!!ops.pending} onClick={()=>act({type:'fail_next'},'다음 공유에서 전달 실패를 재현합니다. 제조기업에서 자료를 승인해 주세요.')}>{ops.failNextDelivery?'다음 전달 실패 시연 준비됨':'다음 전달 실패 상황 재현'}</Button><Button className="primary-action full" disabled={!ops.pending} onClick={()=>act({type:'retry'},'승인본을 다시 전달했습니다. 은행 수신 화면에서 확인할 수 있습니다.')}><Send/>승인본 다시 전달</Button><Button variant="ghost" className="full secondary-action" onClick={()=>changeRole(ops.pending?'bank':'manufacturer')}>업무 화면으로 <ArrowRight/></Button></section><div className="boundary-note"><ShieldCheck size={21}/><p>운영 역할은 전달·오류 이력을 다룹니다. 기업의 공유 승인과 은행의 금융 판단을 대신하지 않습니다.</p></div></aside></div></>}
 <footer><div><span className="save-dot"/>{ready?'이 브라우저에 시연 상태 저장':'시연 상태 불러오는 중'} · 근거 검토는 규칙 기반</div><Button variant="ghost" onClick={()=>setResetOpen(true)}><RotateCcw size={14}/>시연 초기화</Button></footer></div>
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="demo-dialog"><DialogHeader><DialogTitle>{modal==='share'?'은행에 전달할 자료를 확인하세요':modal==='basis'?'운전 근거·생산 조건 확인':modal==='quote'?'견적 v2 변경 영향 확인':'TransitionOps 데모 안내'}</DialogTitle><DialogDescription>{modal==='guide'?'제조기업의 투자 근거 준비부터 은행의 보완 요청까지 한 건으로 살펴봅니다.':modal==='share'?'수신자 BANK-DEMO-IM · 목적: 설비투자 금융상담 근거 확인':'아래 사항을 확인한 뒤 조건부 추정에 반영합니다. 실제 기술 승인이나 시운전 기록은 아닙니다.'}</DialogDescription></DialogHeader>
 {modal==='share'&&<><div className="notice teal"><ShieldCheck size={19}/><span>고객명·레시피·거래 단가·원시 로그·원문 전체는 공유본에 포함하지 않습니다.</span></div>{([{id:'scope',label:'투자 목적·설비 범위',detail:'필수 · 계측 경계와 미확인 항목'},{id:'quote',label:`승인할 견적 v${state.quoteVersion} 요약`,detail:`필수 · 공급가 ${won(currentQuote.capex)}, 부가세 ${won(currentQuote.vat)}`},{id:'energy',label:'조건부 전력 추정·집계 근거',detail:estimate?`선택 · 연 ${n(estimate.saving)}kWh, 가정·근거 발췌 포함`:'운전·견적 조건 확인 후 선택 가능'}] as {id:ShareField;label:string;detail:string}[]).map(f=><label className="check-row" key={f.id}><Checkbox checked={fields.includes(f.id)} disabled={f.id==='energy'&&!estimate} onCheckedChange={v=>setFields(v?[...fields.filter(x=>x!==f.id),f.id]:fields.filter(x=>x!==f.id))}/><div><b>{f.label}</b><p>{f.detail}</p></div></label>)}<label className="check-row consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(Boolean(v))}/><div><b>목적·수신자·선택 항목을 확인하고 공유를 승인합니다.</b><p>제조 공유 승인 담당자의 동작을 시연합니다.</p></div></label>{selectionIssue&&<p role="alert" className="form-error">{selectionIssue}</p>}<Button className="primary-action full" disabled={!consent} onClick={()=>{try{const next=run({type:'share',fields,consent});setMessage(next.pending?'자료는 승인됐지만 전달에 실패했습니다. 운영 화면에서 재전달하세요.':'승인된 새 자료를 은행에 전달했습니다.');setModal(null)}catch(e){setSelectionIssue(e instanceof Error?e.message:'공유할 수 없습니다.')}}}><Send/>선택한 자료 승인·전달</Button></>}
 {(modal==='basis'||modal==='quote')&&<>{(modal==='basis'?['계측 경계가 압축기 패키지와 드라이어를 포함하며 다른 생산설비를 제외함을 확인했습니다.','부하별 시간 1,600/1,600/800h와 동일 조건의 연간 환산 가정을 확인했습니다.','말단 압력·건조·여과 조건을 유지해야 하며 교체 후 시운전 확인이 남음을 확인했습니다.']:['드라이어 추가로 공급가가 700만원, 부가세 포함 지급액이 770만원 증가함을 확인했습니다.','같은 운전 경계에서 드라이어 전력 3→2kW, 추가 절감 연 4,000kWh로 비교했습니다.','압력·공기질 유지와 시운전 조건을 검토했으며, 이전 은행 공유본은 새 승인 전까지 유지합니다.']).map((label,i)=><label className="check-row" key={label}><Checkbox checked={checks[i]} onCheckedChange={v=>setChecks(c=>c.map((x,j)=>i===j?Boolean(v):x))}/><span>{label}</span></label>)}<Button className="primary-action full" disabled={!checks.every(Boolean)} onClick={()=>{if(act({type:modal==='basis'?'review_basis':'review_quote'},'검토한 조건을 반영했습니다. 공유 범위를 확인해 새 자료를 전달할 수 있습니다.'))setModal(null)}}><CheckCircle2/>확인한 조건 반영</Button></>}
 {modal==='guide'&&<div className="guide"><ol><li><b>제조기업</b>에서 상담 준비본을 공유합니다. 절감량은 아직 미산정입니다.</li><li><b>은행 RM</b>에서 보완 요청을 만들고 제조기업으로 돌아갑니다.</li><li>시설 회신을 불러와 조건을 확인하고 전력 추정이 포함된 자료를 공유합니다.</li><li>은행에서 검토 기록을 남긴 뒤, 제조기업에서 변경 견적 v2를 불러옵니다.</li><li>비용·범위·품질 영향을 확인하고 새 자료를 승인합니다. 은행은 새 버전을 재검토합니다.</li></ol><div className="notice teal">원한다면 운영 화면에서 다음 전달 실패를 재현하고 승인본을 재전달할 수 있습니다.</div><h3>세 역할의 책임</h3><div className="role-map"><div><Factory/><b>제조기업</b><span>현장 근거·투자·공유 승인</span></div><ArrowRight/><div><Landmark/><b>은행</b><span>금융 근거·심사 준비</span></div><ArrowRight/><div><Network/><b>인프라·통합 사업자</b><span>구축·연결·운영</span></div></div><h3>이 데모의 범위</h3><p>기업·인물·견적·운전 데이터는 모두 합성입니다. 계산과 상태 전환은 실제 코드로 동작하고, 검토 초안은 근거 규칙으로 생성합니다. 실시간 LLM 호출이나 금융기관 연계는 없습니다.</p><p>역할 탭은 같은 브라우저의 미리보기입니다. 실제 로그인·서버 권한 분리나 금융망 격리를 구현한 것은 아닙니다. 원문 자료도 합성 예제로 내려갑니다. 내보내는 공유본은 선택한 항목으로 별도 구성합니다.</p><h3>참고한 공식 자료</h3>{scenario.public_references.map(r=><a className="reference-link" key={r.id} href={r.url} target="_blank" rel="noreferrer">{r.title}<ExternalLink size={14}/></a>)}<p className="source-note">공식 자료는 계측·압력·공기질 검토 원리의 근거입니다. 데모의 수치·설비 성능·단가는 공식 자료에서 가져온 실측값이 아닙니다.</p></div>}
 </DialogContent></Dialog>
 <Dialog open={!!doc} onOpenChange={open=>{if(!open)setDoc(null)}}><DialogContent className="demo-dialog document-dialog"><DialogHeader><DialogTitle>{doc?.title}</DialogTitle><DialogDescription>제조기업 내부 자료 · 합성 원문</DialogDescription></DialogHeader><pre className="document-text">{doc?.content}</pre></DialogContent></Dialog>
 <Dialog open={!!selectedPackage} onOpenChange={open=>{if(!open)setSelectedPackage(null)}}><DialogContent className="demo-dialog"><DialogHeader><DialogTitle>{selectedPackage?.id}</DialogTitle><DialogDescription>공유 당시 내용이 유지되는 승인 자료</DialogDescription></DialogHeader>{selectedPackage&&<><PackageBody p={selectedPackage}/><Button variant="outline" onClick={()=>exportPackage(selectedPackage)}><Download/>이 버전 내려받기</Button></>}</DialogContent></Dialog>
 <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>시연을 처음부터 시작할까요?</AlertDialogTitle><AlertDialogDescription>이 브라우저에 저장된 공유본과 처리 이력을 지우고 초기 자료로 돌아갑니다. 내려받은 파일은 유지됩니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>계속 보기</AlertDialogCancel><AlertDialogAction onClick={()=>{commit(initialState());setResetOpen(false);changeRole('manufacturer');setMessage('초기 시연 자료로 돌아왔습니다.')}}>초기화</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
